# Generated by Django 5.0.2 on 2024-03-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='craeted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
